# Generated by Django 5.0.14 on 2026-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="ISO 4217, e.g. EUR, GBP, UZS.", max_length=3, unique=True
                    ),
                ),
                (
                    "rate_from_usd",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="1 USD = this many units of `currency`.",
                        max_digits=14,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["currency"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=32)),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Digits only, no '+', e.g. 998953336000", max_length=32
                    ),
                ),
                ("telegram_username", models.CharField(max_length=64)),
                ("instagram_username", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("office_address", models.CharField(max_length=255)),
                ("working_hours", models.CharField(max_length=255)),
                (
                    "response_time_promise",
                    models.CharField(
                        help_text="e.g. 'We reply within 1 hour' — shown near booking CTAs.",
                        max_length=255,
                    ),
                ),
                ("default_og_image", models.ImageField(blank=True, null=True, upload_to="site/")),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
