# Generated by Django 5.0.14 on 2026-08-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_routepage"),
        ("core", "0002_seed_site_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("rating", models.PositiveSmallIntegerField(help_text="1–5")),
                ("body", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GOOGLE", "Google"),
                            ("TRIPADVISOR", "TripAdvisor"),
                            ("DIRECT", "Direct / WhatsApp"),
                            ("OTHER", "Other"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="Link to the original review, if public."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Only verified, real reviews should be published."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="catalog.destination",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="catalog.package",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
