# Generated by Django 5.2.17 on 2026-08-29 09:15

from django.db import migrations, models

PLACEHOLDER = "TODO: confirm with Abdulloh"
PLACEHOLDER_FIELDS = ("email", "office_address", "working_hours", "response_time_promise")


def clear_placeholder_text(apps, schema_editor):
    # 0002_seed_site_settings stuffed this literal string into these fields,
    # including the EmailField — which fails admin validation on save and
    # was rendering raw on the public site (footer, contact page, etc.).
    # Blank the placeholder out now that the fields allow it.
    SiteSettings = apps.get_model("core", "SiteSettings")
    settings_obj = SiteSettings.objects.filter(pk=1).first()
    if settings_obj is None:
        return
    changed = False
    for field_name in PLACEHOLDER_FIELDS:
        if getattr(settings_obj, field_name) == PLACEHOLDER:
            setattr(settings_obj, field_name, "")
            changed = True
    if changed:
        settings_obj.save(update_fields=PLACEHOLDER_FIELDS)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="office_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="response_time_promise",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'We reply within 1 hour' — shown near booking CTAs.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(clear_placeholder_text, noop_reverse),
    ]
