# Generated by Django 5.2.17 on 2026-08-29 09:50

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_sitesettings_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_og_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_og_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="default_og_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="default_og_image_height",
                null=True,
                upload_to="site/",
                width_field="default_og_image_width",
            ),
        ),
    ]
