# Generated by Django 5.0.14 on 2026-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_description_en", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_de", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_es", models.CharField(blank=True, max_length=320, null=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=255)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("noindex", models.BooleanField(default=False)),
                ("translation_complete_ru", models.BooleanField(default=False)),
                ("translation_complete_de", models.BooleanField(default=False)),
                ("translation_complete_fr", models.BooleanField(default=False)),
                ("translation_complete_es", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_de", models.CharField(max_length=255, null=True)),
                ("title_fr", models.CharField(max_length=255, null=True)),
                ("title_es", models.CharField(max_length=255, null=True)),
                ("excerpt", models.CharField(blank=True, max_length=320)),
                ("excerpt_en", models.CharField(blank=True, max_length=320, null=True)),
                ("excerpt_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("excerpt_de", models.CharField(blank=True, max_length=320, null=True)),
                ("excerpt_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("excerpt_es", models.CharField(blank=True, max_length=320, null=True)),
                ("body", models.TextField(blank=True, help_text="Rich text body (HTML).")),
                (
                    "body_en",
                    models.TextField(blank=True, help_text="Rich text body (HTML).", null=True),
                ),
                (
                    "body_ru",
                    models.TextField(blank=True, help_text="Rich text body (HTML).", null=True),
                ),
                (
                    "body_de",
                    models.TextField(blank=True, help_text="Rich text body (HTML).", null=True),
                ),
                (
                    "body_fr",
                    models.TextField(blank=True, help_text="Rich text body (HTML).", null=True),
                ),
                (
                    "body_es",
                    models.TextField(blank=True, help_text="Rich text body (HTML).", null=True),
                ),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                ("author", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Review"),
                            ("PUBLISHED", "Published"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "related_destinations",
                    models.ManyToManyField(
                        blank=True, related_name="related_posts", to="catalog.destination"
                    ),
                ),
                (
                    "related_packages",
                    models.ManyToManyField(
                        blank=True, related_name="related_posts", to="catalog.package"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
