# Generated by Django 5.2.17 on 2026-08-29 09:50

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="cover_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="cover_image_height",
                null=True,
                upload_to="blog/",
                width_field="cover_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="og_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="og_image_height",
                null=True,
                upload_to="seo/",
                width_field="og_image_width",
            ),
        ),
    ]
