# Generated by Django 5.2.17 on 2026-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_cover_image_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="body_ar",
            field=models.TextField(blank=True, help_text="Rich text body (HTML).", null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt_ar",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="translation_complete_ar",
            field=models.BooleanField(default=False),
        ),
    ]
