# Generated by Django 5.0.14 on 2026-08-28 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuilderSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("last_step", models.PositiveSmallIntegerField(default=1)),
                (
                    "estimated_total_usd",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("is_converted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ref_code", models.CharField(editable=False, max_length=16, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct request"),
                            ("BUILDER", "Tour builder"),
                            ("PACKAGE", "Package page"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw builder selection, if source_type=BUILDER.",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("adults", models.PositiveSmallIntegerField(default=1)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("whatsapp", models.CharField(blank=True, max_length=32)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                ("preferred_language", models.CharField(default="en", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUOTED", "Quoted"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_total_usd",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "quoted_total_usd",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_requests",
                        to="catalog.package",
                    ),
                ),
                (
                    "vehicle_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_requests",
                        to="catalog.vehicleclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("TRANSPORT", "Transport"),
                            ("ACTIVITY", "Activity"),
                            ("ADDON", "Add-on"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("unit_price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ("subtotal_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bookings.bookingrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
