# Generated by Django 5.0.14 on 2026-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingrequest",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="country"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="full name"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="message",
            field=models.TextField(blank=True, verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=32, verbose_name="WhatsApp"),
        ),
    ]
