# Generated by Django 5.0.14 on 2026-08-28 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PER_PERSON", "Per person"),
                            ("PER_DAY", "Per day"),
                            ("PER_GROUP", "Per group"),
                            ("PER_NIGHT", "Per night"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_description_en", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_de", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_es", models.CharField(blank=True, max_length=320, null=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=255)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("noindex", models.BooleanField(default=False)),
                ("translation_complete_ru", models.BooleanField(default=False)),
                ("translation_complete_de", models.BooleanField(default=False)),
                ("translation_complete_fr", models.BooleanField(default=False)),
                ("translation_complete_es", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_de", models.CharField(max_length=255, null=True)),
                ("name_fr", models.CharField(max_length=255, null=True)),
                ("name_es", models.CharField(max_length=255, null=True)),
                ("region", models.CharField(blank=True, max_length=255)),
                ("region_en", models.CharField(blank=True, max_length=255, null=True)),
                ("region_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("region_de", models.CharField(blank=True, max_length=255, null=True)),
                ("region_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("region_es", models.CharField(blank=True, max_length=255, null=True)),
                ("hero_image", models.ImageField(blank=True, null=True, upload_to="destinations/")),
                ("intro", models.TextField(blank=True)),
                ("intro_en", models.TextField(blank=True, null=True)),
                ("intro_ru", models.TextField(blank=True, null=True)),
                ("intro_de", models.TextField(blank=True, null=True)),
                ("intro_fr", models.TextField(blank=True, null=True)),
                ("intro_es", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True, null=True)),
                ("body_ru", models.TextField(blank=True, null=True)),
                ("body_de", models.TextField(blank=True, null=True)),
                ("body_fr", models.TextField(blank=True, null=True)),
                ("body_es", models.TextField(blank=True, null=True)),
                ("min_recommended_days", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "languages",
                    models.CharField(blank=True, help_text="Comma-separated.", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_description_en", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_de", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_es", models.CharField(blank=True, max_length=320, null=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=255)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("noindex", models.BooleanField(default=False)),
                ("translation_complete_ru", models.BooleanField(default=False)),
                ("translation_complete_de", models.BooleanField(default=False)),
                ("translation_complete_fr", models.BooleanField(default=False)),
                ("translation_complete_es", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_de", models.CharField(max_length=255, null=True)),
                ("title_fr", models.CharField(max_length=255, null=True)),
                ("title_es", models.CharField(max_length=255, null=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Economy"),
                            ("STANDARD", "Standard"),
                            ("PREMIUM", "Premium"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("total_days", models.PositiveSmallIntegerField()),
                ("summary", models.CharField(blank=True, max_length=320)),
                ("summary_en", models.CharField(blank=True, max_length=320, null=True)),
                ("summary_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("summary_de", models.CharField(blank=True, max_length=320, null=True)),
                ("summary_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("summary_es", models.CharField(blank=True, max_length=320, null=True)),
                ("body", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True, null=True)),
                ("body_ru", models.TextField(blank=True, null=True)),
                ("body_de", models.TextField(blank=True, null=True)),
                ("body_fr", models.TextField(blank=True, null=True)),
                ("body_es", models.TextField(blank=True, null=True)),
                ("hero_image", models.ImageField(blank=True, null=True, upload_to="packages/")),
                ("gallery", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("plate", models.CharField(blank=True, max_length=32)),
                (
                    "is_partner",
                    models.BooleanField(
                        default=False,
                        help_text="Third-party partner vehicle rather than company-owned.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("daily_cost_usd", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                "ordering": ["vehicle_class", "name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_pax", models.PositiveSmallIntegerField()),
                ("max_pax", models.PositiveSmallIntegerField()),
                ("daily_rate_usd", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image", models.ImageField(blank=True, null=True, upload_to="vehicle_classes/")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "min_pax"],
            },
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image paths/URLs."
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("entry_fee_usd", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "typical_duration_min",
                    models.PositiveIntegerField(
                        default=60, help_text="Typical visit duration, in minutes."
                    ),
                ),
                ("is_bookable", models.BooleanField(default=False)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attractions",
                        to="catalog.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["destination__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_description_en", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_de", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_es", models.CharField(blank=True, max_length=320, null=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=255)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("noindex", models.BooleanField(default=False)),
                ("translation_complete_ru", models.BooleanField(default=False)),
                ("translation_complete_de", models.BooleanField(default=False)),
                ("translation_complete_fr", models.BooleanField(default=False)),
                ("translation_complete_es", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_de", models.CharField(max_length=255, null=True)),
                ("title_fr", models.CharField(max_length=255, null=True)),
                ("title_es", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("PER_VEHICLE", "Per vehicle (flat, per group)"),
                            ("PER_PERSON", "Per person"),
                            ("PER_DAY", "Per day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_price_usd", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_hours", models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ("images", models.JSONField(blank=True, default=list)),
                ("short_desc", models.CharField(blank=True, max_length=320)),
                ("short_desc_en", models.CharField(blank=True, max_length=320, null=True)),
                ("short_desc_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("short_desc_de", models.CharField(blank=True, max_length=320, null=True)),
                ("short_desc_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("short_desc_es", models.CharField(blank=True, max_length=320, null=True)),
                ("full_desc", models.TextField(blank=True)),
                ("full_desc_en", models.TextField(blank=True, null=True)),
                ("full_desc_ru", models.TextField(blank=True, null=True)),
                ("full_desc_de", models.TextField(blank=True, null=True)),
                ("full_desc_fr", models.TextField(blank=True, null=True)),
                ("full_desc_es", models.TextField(blank=True, null=True)),
                ("included", models.TextField(blank=True, help_text="One item per line.")),
                (
                    "included_en",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "included_ru",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "included_de",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "included_fr",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "included_es",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                ("not_included", models.TextField(blank=True, help_text="One item per line.")),
                (
                    "not_included_en",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "not_included_ru",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "not_included_de",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "not_included_fr",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "not_included_es",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="catalog.destination",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["destination__order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PackageDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="catalog.package",
                    ),
                ),
            ],
            options={
                "ordering": ["package", "day_number"],
                "unique_together": {("package", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="PackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "custom_label",
                    models.CharField(
                        blank=True,
                        help_text="Used when neither activity nor addon applies.",
                        max_length=255,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_items",
                        to="catalog.activity",
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_items",
                        to="catalog.addon",
                    ),
                ),
                (
                    "package_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.packageday",
                    ),
                ),
            ],
            options={
                "ordering": ["package_day", "id"],
            },
        ),
        migrations.CreateModel(
            name="SeasonalRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="e.g. 1.20 for +20% peak season.",
                        max_digits=4,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to apply this rate globally to all activities.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_rates",
                        to="catalog.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["date_from"],
            },
        ),
        migrations.CreateModel(
            name="BlackoutDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to block this date for the entire fleet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackout_dates",
                        to="catalog.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="catalog.vehicleclass",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="base_vehicle_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="catalog.vehicleclass",
            ),
        ),
    ]
