# Generated by Django 5.0.14 on 2026-08-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_packageday_description_de_packageday_description_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_description_en", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_de", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_es", models.CharField(blank=True, max_length=320, null=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=255)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("noindex", models.BooleanField(default=False)),
                ("translation_complete_ru", models.BooleanField(default=False)),
                ("translation_complete_de", models.BooleanField(default=False)),
                ("translation_complete_fr", models.BooleanField(default=False)),
                ("translation_complete_es", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "destination_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_pages_as_a",
                        to="catalog.destination",
                    ),
                ),
                (
                    "destination_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_pages_as_b",
                        to="catalog.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "slug"],
                "unique_together": {("destination_a", "destination_b")},
            },
        ),
    ]
