# Generated by Django 5.2.17 on 2026-08-29 09:50

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_routepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="og_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="og_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="hero_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="hero_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="og_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="og_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="hero_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="hero_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="og_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="og_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="routepage",
            name="og_image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="routepage",
            name="og_image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vehicleclass",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vehicleclass",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="og_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="og_image_height",
                null=True,
                upload_to="seo/",
                width_field="og_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="hero_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="hero_image_height",
                null=True,
                upload_to="destinations/",
                width_field="hero_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="og_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="og_image_height",
                null=True,
                upload_to="seo/",
                width_field="og_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="hero_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="hero_image_height",
                null=True,
                upload_to="packages/",
                width_field="hero_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="og_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="og_image_height",
                null=True,
                upload_to="seo/",
                width_field="og_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="routepage",
            name="og_image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="og_image_height",
                null=True,
                upload_to="seo/",
                width_field="og_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleclass",
            name="image",
            field=apps.core.fields.WebPImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to="vehicle_classes/",
                width_field="image_width",
            ),
        ),
    ]
