# Generated by Django 5.2.17 on 2026-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_activity_og_image_height_activity_og_image_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="full_desc_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="included_ar",
            field=models.TextField(blank=True, help_text="One item per line.", null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="meta_title_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="not_included_ar",
            field=models.TextField(blank=True, help_text="One item per line.", null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="short_desc_ar",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="translation_complete_ar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="destination",
            name="body_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="intro_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="meta_title_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="name_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="region_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="translation_complete_ar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="package",
            name="body_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="meta_title_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="summary_ar",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="translation_complete_ar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="packageday",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packageday",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="routepage",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name="routepage",
            name="meta_title_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="routepage",
            name="translation_complete_ar",
            field=models.BooleanField(default=False),
        ),
    ]
