# Generated by Django 5.2.17 on 2026-09-01 17:35

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_activity_full_desc_ar_activity_included_ar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ar", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_description_en", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_de", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_es", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ar", models.CharField(blank=True, max_length=320, null=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    apps.core.fields.WebPImageField(
                        blank=True,
                        height_field="og_image_height",
                        null=True,
                        upload_to="seo/",
                        width_field="og_image_width",
                    ),
                ),
                (
                    "og_image_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "og_image_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("noindex", models.BooleanField(default=False)),
                ("translation_complete_ru", models.BooleanField(default=False)),
                ("translation_complete_de", models.BooleanField(default=False)),
                ("translation_complete_fr", models.BooleanField(default=False)),
                ("translation_complete_es", models.BooleanField(default=False)),
                ("translation_complete_ar", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_de", models.CharField(max_length=255, null=True)),
                ("name_fr", models.CharField(max_length=255, null=True)),
                ("name_es", models.CharField(max_length=255, null=True)),
                ("name_ar", models.CharField(max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SEDAN", "Sedan"),
                            ("SUV", "SUV"),
                            ("MINIVAN", "Minivan"),
                            ("MINIBUS", "Minibus"),
                            ("BUS", "Bus"),
                        ],
                        default="SEDAN",
                        max_length=20,
                    ),
                ),
                ("capacity_pax", models.PositiveSmallIntegerField(default=1)),
                ("trunk_capacity_desc", models.CharField(blank=True, max_length=255)),
                ("trunk_capacity_desc_en", models.CharField(blank=True, max_length=255, null=True)),
                ("trunk_capacity_desc_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("trunk_capacity_desc_de", models.CharField(blank=True, max_length=255, null=True)),
                ("trunk_capacity_desc_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("trunk_capacity_desc_es", models.CharField(blank=True, max_length=255, null=True)),
                ("trunk_capacity_desc_ar", models.CharField(blank=True, max_length=255, null=True)),
                ("daily_rate_usd", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("description_ar", models.TextField(blank=True, null=True)),
                (
                    "hero_image",
                    apps.core.fields.WebPImageField(
                        blank=True,
                        height_field="hero_image_height",
                        null=True,
                        upload_to="cars/",
                        width_field="hero_image_width",
                    ),
                ),
                (
                    "hero_image_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "hero_image_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("gallery", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "vehicle_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cars",
                        to="catalog.vehicleclass",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_title_ar", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                ("meta_description_en", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ru", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_de", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_fr", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_es", models.CharField(blank=True, max_length=320, null=True)),
                ("meta_description_ar", models.CharField(blank=True, max_length=320, null=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    apps.core.fields.WebPImageField(
                        blank=True,
                        height_field="og_image_height",
                        null=True,
                        upload_to="seo/",
                        width_field="og_image_width",
                    ),
                ),
                (
                    "og_image_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "og_image_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("noindex", models.BooleanField(default=False)),
                ("translation_complete_ru", models.BooleanField(default=False)),
                ("translation_complete_de", models.BooleanField(default=False)),
                ("translation_complete_fr", models.BooleanField(default=False)),
                ("translation_complete_es", models.BooleanField(default=False)),
                ("translation_complete_ar", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_de", models.CharField(max_length=255, null=True)),
                ("name_fr", models.CharField(max_length=255, null=True)),
                ("name_es", models.CharField(max_length=255, null=True)),
                ("name_ar", models.CharField(max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUDGET", "Budget"),
                            ("STANDARD", "Standard"),
                            ("BOUTIQUE", "Boutique"),
                            ("LUXURY", "Luxury"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("address_en", models.CharField(blank=True, max_length=255, null=True)),
                ("address_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("address_de", models.CharField(blank=True, max_length=255, null=True)),
                ("address_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("address_es", models.CharField(blank=True, max_length=255, null=True)),
                ("address_ar", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("description_ar", models.TextField(blank=True, null=True)),
                ("amenities", models.TextField(blank=True, help_text="One item per line.")),
                (
                    "amenities_en",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "amenities_ru",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "amenities_de",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "amenities_fr",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "amenities_es",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "amenities_ar",
                    models.TextField(blank=True, help_text="One item per line.", null=True),
                ),
                (
                    "price_per_night_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "hero_image",
                    apps.core.fields.WebPImageField(
                        blank=True,
                        height_field="hero_image_height",
                        null=True,
                        upload_to="hotels/",
                        width_field="hero_image_width",
                    ),
                ),
                (
                    "hero_image_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "hero_image_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("gallery", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotels",
                        to="catalog.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
