# Generated by Django 5.2.17 on 2026-09-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_car_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="images",
        ),
        migrations.RemoveField(
            model_name="attraction",
            name="images",
        ),
        migrations.RemoveField(
            model_name="car",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="package",
            name="gallery",
        ),
    ]
